apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: { app: my-app }
  template:
    metadata: { labels: { app: my-app } }
    spec:
      containers:
        - name: my-app
          image: 10.0.0.11:8082/my-app:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
