services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus-data-vol:/nexus-data    

  jenkins:
    jenkins:
    build: ./jenkins        
    container_name: jenkins
    user: root
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - jenkins-home-vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  nexus-data-vol:
  jenkins-home-vol:
