apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac
  template:
    metadata:
      labels:
        app: tic-tac
    spec:
      imagePullSecrets:
        - name: nexus-docker # secret created in cluster
      containers:
        - name: tic-tac-container
          image: 10.100.102.175:8082/tic-tac-toe:latest # Jenkins will replace :latest with :<BUILD_NUMBER>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tic-tac-svc
spec:
  type: NodePort
  selector:
    app: tic-tac
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
